name: Analyzers lib

on:

  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/services/common/Codebreaker.GameAPIs.Analyzers/**'
    - 'src/services/common/Codebreaker.GameAPIs.Analyzers.Tests/**'

  # Allow manually trigger 
  workflow_dispatch:    

jobs:
  build:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/createnuget-withbuildnumber.yml@main
    with:
      version-suffix: preview.1.
      version-number: ${{ github.run_number }}
      version-offset: 38
      solutionfile-path: src/Codebreaker.Analyzers.slnx
      projectfile-path: src/services/common/Codebreaker.GameAPIs.Analyzers/Codebreaker.Analyzers.csproj
      dotnet-version: '9.0.x'
      artifact-name: codebreaker-analyzers
      branch-name: main

  publishdevops:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-azuredevops.yml@main
    needs: build
    with:
      artifact-name: codebreaker-analyzers
    secrets: inherit

  # NuGet publish is now done with codebreaker-lib-stable.yml
  # In case a preview version will be published again to NuGet, this can be uncommented.
  # publishnuget:
  #   uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-nugetserver.yml@main
  #   needs: publishdevops
  #   with:
  #     artifact-name: codebreaker-analyzers
  #   secrets: inherit
